### ISSUE TITLE
illegal start of expression

### ISSUE THREAD

**Issue by p4u1d34n** [Fir3st/capacitor-calendar#14]
`if (allDayEventConfig !== null) {`

causing

```
error: illegal start of expression
            if (allDayEventConfig !== null) {
```

changed to

`if ( allDayEventConfig ) {`
  
on lines

132, 408

in 

... /node_modules/capacitor-calendar/android/src/main/java/cz/firest/calendar/CapacitorCalendar.java

**Comment by Fir3st** [comment]
Thanks for your report! I didn't realize in #11 there is no type comparison in java 🙃

**Comment by p4u1d34n** [comment]
With so many Syntactical similarities between languages, it's an understandable faux par.
